server:
  port: 9005

spring:
  application:
    name: txf-chat
    # ASUS
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://localhost:3306/senstive_word?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=Asia/Shanghai
#    username: root
#    password: 123456
  datasource:
    dynamic:
      strict: false
      primary: master
      datasource:
        master:
          type: com.alibaba.druid.pool.DruidDataSource
          username: root
          password: TXFtxf1121512752
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/senstive_words?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=Asia/Shanghai
        txf:
          type: com.alibaba.druid.pool.DruidDataSource
          username: root
          password: TXFtxf1121512752
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/txf_club_db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=Asia/Shanghai
white:
  urls:
    - "/chatUser/login"